name: Receive

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    name: Build and publish
    env:
        ref: ${{ github.event.client_payload.ref }}
    steps:
      - name: Output text
        run: echo "Here is some output $ref"
