name: Receive

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref'
        required: true
        type: string      
      sha:
        description: 'Git sha'
        required: true
        type: string        

jobs:
  echo:
    runs-on: ubuntu-latest
    name: Build and publish
    steps:
      - name: Output inputs
        run: echo '${{ inputs.ref }}, ${{ inputs.sha }}'
